## 선형대수 (Linear Algebra) 

- 데이타 분석에 필요한 계산(?)

### 데이타 유형

1. 스칼라(scalar) : 하나의 값으로 이루어진 데이타
2. 벡터(vector) : 여러개의 값으로 이루어진 데이타 (= 데이타 레코드)
3. 행렬(matrix) : 벡터가 여러개인 데이터 집합


### numpy 에서 벡터를 표현 할 때
1. numpy에서도 1차원 배열 객체도 벡터이다 
    + x1 = np.array([2.1, 2.2, 2.3])    
    

2. 벡터를 열의 개수가 하나인 2차원 배열 객체로 표현하는 것이 올바르다
    + x1 = np.array([[2.1], [2.2], [2.3]])


In [1]:
import numpy as np

In [8]:
x1 = np.array([1, 2, 3])  # 행벡터 - row vector
print(x1)

x1 = np.array([[1], [2], [3]]) # 열벡터 - columns vector
print(x1)

[1 2 3]
[[1]
 [2]
 [3]]


### 행렬
    - 하나의 데이터 레코드를 단독 벡터로 나타낼때는 하나의 열로 나타낸다.
    - 하나의 데이터 레코드를 벡터로 표현할 때도 하나의 열로 나타낸다
    - 복수의 데이타 레코드 집합을 행렬로 표현할 때는 하나의 데이타 레코드 행으로 표현된다.
    - 뭔말이야??????

#### 1.전치행렬 : 전치 연산으로 만들어진 행렬

   ** 전치 연산 : T
    - 행렬에서 가장 기본이 되는 연산
    - 행과 열을 바꾸는 연산
    
   1.  벡터 x(열벡터)에 대한 전치 연산을 하면 행벡터(row vector)가 된다
   
   2. 벡터 x(행벡터)에 대해서는 변화가 없다

In [13]:
#  1.벡터 x(열벡터)에 대한 전치 연산을 하면 행벡터(row vector)가 된다

x1 = np.array([[2],[3],[4],[5]])
print(x1)

# T는 메소드가 아니라 속성이다
print(x1.T)


#  2. 벡터 x(행벡터)에 대해서는 변화가 없다
x2 = np.array([10,20, 30])
print(x2)
print(x2.T)

[[2]
 [3]
 [4]
 [5]]
[[2 3 4 5]]
[10 20 30]
[10 20 30]


#### 2. 다양한 행렬

- 정방행렬 : 행과 열의개수가 같은행렬 (square matrix)


- 대각행렬 :  주대각선을 제외한 곳의 원소가 모두 0인 정사각행렬이다.
           ( 대각행렬은 0일 수도, 아닐 수도 있는 대각원소들에 의해 결정된다 )
            numpy의 diag ()로 생성
            
- 단위행렬 : 대각행렬 중에서 모든 대각 성분의 값이 1인 대각행렬 (identity matrix) 
            ( 항등행렬이라고도 함 )

- 대칭행렬 : 전치연산을 통해 얻은 전치행렬과 원래 행렬이 같은 경우 (symmetric matrix)
            ( 단, 대칭행렬은 정방행렬이여야 한다 )


#### 3. 특수벡터

+ 0벡터 
+ 1벡터

In [18]:
# 특수행렬
print(np.ones( 10 )) # 1로 채원진 10 크기의 (1차원) 배열 생성

print(np.zeros( (5,5) )) # 0으로 채원진 5x5 크기의 배열 생성

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# 대각행렬
d = np.diag([1, 2, 3])
print(d)

# 단위행렬
i= np.identity(3)
print(i)

i2 = np.eye(4) # identiry()와 동일
print(i2)

# 대칭행렬


[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### [참고] 데이타 사이언스 스쿨

